const TOGGLE_EDITING_TITLE = 'TOGGLE_EDITING_TITLE';
const TOGGLE_EDITING_DEADLINE = 'TOGGLE_EDITING_DEADLINE';
const TOGGLE_DELETING_TODO = 'TOGGLE_DELETING_TODO';
const TOGGLE_TODO_PANEL = 'TOGGLE_TODO_PANEL';
const SET_ACTIVE_TODO = 'SET_ACTIVE_TODO';

export {
    TOGGLE_EDITING_TITLE,
    TOGGLE_EDITING_DEADLINE,
    TOGGLE_DELETING_TODO,
    TOGGLE_TODO_PANEL,
    SET_ACTIVE_TODO
}